does this work?

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -4,7 +4,7 @@ on:
   push:
 
 jobs:
-  pre-commit:
+  testing:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
@@ -25,6 +25,18 @@ jobs:
       - name: Run lint
         run: npm run lint
       - name: Start the app
-        run: npm run start
+        run: nohup npm run start &
+      - name: Wait for app
+        run: |
+          for i in {1..30}; do
+            if nc -z localhost 3000; then
+              echo "App is up!"
+              exit 0
+            fi
+            echo "Waiting..."
+            sleep 1
+          done
+          echo "App failed to start"
+          exit 1
       - name: Run tests
         run: npm run test
